class GithubSearchRepositoryMockData {
  static const String jsonData = '''
  {
  "total_count": 2,
  "incomplete_results": false,
  "items": [
    {
      "id": 31792824,
      "node_id": "MDEwOlJlcG9zaXRvcnkzMTc5MjgyNA==",
      "name": "flutter",
      "full_name": "flutter/flutter",
      "private": false,
      "owner": {
          "login": "flutter",
          "id": 14101776,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2",
          "avatar_url": "https://avatars.githubusercontent.com/u/14101776?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/flutter",
          "html_url": "https://github.com/flutter",
          "followers_url": "https://api.github.com/users/flutter/followers",
          "following_url": "https://api.github.com/users/flutter/following{/other_user}",
          "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
          "organizations_url": "https://api.github.com/users/flutter/orgs",
          "repos_url": "https://api.github.com/users/flutter/repos",
          "events_url": "https://api.github.com/users/flutter/events{/privacy}",
          "received_events_url": "https://api.github.com/users/flutter/received_events",
          "type": "Organization",
          "user_view_type": "public",
          "site_admin": false
      },
      "html_url": "https://github.com/flutter/flutter",
      "description": "Flutter makes it easy and fast to build beautiful apps for mobile and beyond",
      "fork": false,
      "url": "https://api.github.com/repos/flutter/flutter",
      "forks_url": "https://api.github.com/repos/flutter/flutter/forks",
      "keys_url": "https://api.github.com/repos/flutter/flutter/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/flutter/flutter/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/flutter/flutter/teams",
      "hooks_url": "https://api.github.com/repos/flutter/flutter/hooks",
      "issue_events_url": "https://api.github.com/repos/flutter/flutter/issues/events{/number}",
      "events_url": "https://api.github.com/repos/flutter/flutter/events",
      "assignees_url": "https://api.github.com/repos/flutter/flutter/assignees{/user}",
      "branches_url": "https://api.github.com/repos/flutter/flutter/branches{/branch}",
      "tags_url": "https://api.github.com/repos/flutter/flutter/tags",
      "blobs_url": "https://api.github.com/repos/flutter/flutter/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/flutter/flutter/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/flutter/flutter/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/flutter/flutter/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/flutter/flutter/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/flutter/flutter/languages",
      "stargazers_url": "https://api.github.com/repos/flutter/flutter/stargazers",
      "contributors_url": "https://api.github.com/repos/flutter/flutter/contributors",
      "subscribers_url": "https://api.github.com/repos/flutter/flutter/subscribers",
      "subscription_url": "https://api.github.com/repos/flutter/flutter/subscription",
      "commits_url": "https://api.github.com/repos/flutter/flutter/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/flutter/flutter/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/flutter/flutter/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/flutter/flutter/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/flutter/flutter/contents/{+path}",
      "compare_url": "https://api.github.com/repos/flutter/flutter/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/flutter/flutter/merges",
      "archive_url": "https://api.github.com/repos/flutter/flutter/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/flutter/flutter/downloads",
      "issues_url": "https://api.github.com/repos/flutter/flutter/issues{/number}",
      "pulls_url": "https://api.github.com/repos/flutter/flutter/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/flutter/flutter/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/flutter/flutter/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/flutter/flutter/labels{/name}",
      "releases_url": "https://api.github.com/repos/flutter/flutter/releases{/id}",
      "deployments_url": "https://api.github.com/repos/flutter/flutter/deployments",
      "created_at": "2015-03-06T22:54:58Z",
      "updated_at": "2025-02-25T09:05:48Z",
      "pushed_at": "2025-02-25T08:04:48Z",
      "git_url": "git://github.com/flutter/flutter.git",
      "ssh_url": "git@github.com:flutter/flutter.git",
      "clone_url": "https://github.com/flutter/flutter.git",
      "svn_url": "https://github.com/flutter/flutter",
      "homepage": "https://flutter.dev",
      "size": 294084,
      "stargazers_count": 168826,
      "watchers_count": 168826,
      "language": "Dart",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 28079,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 13247,
      "license": {
          "key": "bsd-3-clause",
          "name": "BSD 3-Clause New or Revised License",
          "spdx_id": "BSD-3-Clause",
          "url": "https://api.github.com/licenses/bsd-3-clause",
          "node_id": "MDc6TGljZW5zZTU="
      },
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [
          "android",
          "app-framework",
          "cross-platform",
          "dart",
          "dart-platform",
          "desktop",
          "flutter",
          "flutter-package",
          "fuchsia",
          "ios",
          "linux-desktop",
          "macos",
          "material-design",
          "mobile",
          "mobile-development",
          "skia",
          "web",
          "web-framework",
          "windows"
      ],
      "visibility": "public",
      "forks": 28079,
      "open_issues": 13247,
      "watchers": 168826,
      "default_branch": "master",
      "score": 1.0
    },
    {
      "id": 136667574,
      "node_id": "MDEwOlJlcG9zaXRvcnkxMzY2Njc1NzQ=",
      "name": "samples",
      "full_name": "flutter/samples",
      "private": false,
      "owner": {
          "login": "flutter",
          "id": 14101776,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2",
          "avatar_url": "https://avatars.githubusercontent.com/u/14101776?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/flutter",
          "html_url": "https://github.com/flutter",
          "followers_url": "https://api.github.com/users/flutter/followers",
          "following_url": "https://api.github.com/users/flutter/following{/other_user}",
          "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
          "organizations_url": "https://api.github.com/users/flutter/orgs",
          "repos_url": "https://api.github.com/users/flutter/repos",
          "events_url": "https://api.github.com/users/flutter/events{/privacy}",
          "received_events_url": "https://api.github.com/users/flutter/received_events",
          "type": "Organization",
          "user_view_type": "public",
          "site_admin": false
      },
      "html_url": "https://github.com/flutter/samples",
      "description": "A collection of Flutter examples and demos",
      "fork": false,
      "url": "https://api.github.com/repos/flutter/samples",
      "forks_url": "https://api.github.com/repos/flutter/samples/forks",
      "keys_url": "https://api.github.com/repos/flutter/samples/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/flutter/samples/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/flutter/samples/teams",
      "hooks_url": "https://api.github.com/repos/flutter/samples/hooks",
      "issue_events_url": "https://api.github.com/repos/flutter/samples/issues/events{/number}",
      "events_url": "https://api.github.com/repos/flutter/samples/events",
      "assignees_url": "https://api.github.com/repos/flutter/samples/assignees{/user}",
      "branches_url": "https://api.github.com/repos/flutter/samples/branches{/branch}",
      "tags_url": "https://api.github.com/repos/flutter/samples/tags",
      "blobs_url": "https://api.github.com/repos/flutter/samples/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/flutter/samples/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/flutter/samples/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/flutter/samples/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/flutter/samples/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/flutter/samples/languages",
      "stargazers_url": "https://api.github.com/repos/flutter/samples/stargazers",
      "contributors_url": "https://api.github.com/repos/flutter/samples/contributors",
      "subscribers_url": "https://api.github.com/repos/flutter/samples/subscribers",
      "subscription_url": "https://api.github.com/repos/flutter/samples/subscription",
      "commits_url": "https://api.github.com/repos/flutter/samples/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/flutter/samples/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/flutter/samples/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/flutter/samples/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/flutter/samples/contents/{+path}",
      "compare_url": "https://api.github.com/repos/flutter/samples/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/flutter/samples/merges",
      "archive_url": "https://api.github.com/repos/flutter/samples/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/flutter/samples/downloads",
      "issues_url": "https://api.github.com/repos/flutter/samples/issues{/number}",
      "pulls_url": "https://api.github.com/repos/flutter/samples/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/flutter/samples/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/flutter/samples/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/flutter/samples/labels{/name}",
      "releases_url": "https://api.github.com/repos/flutter/samples/releases{/id}",
      "deployments_url": "https://api.github.com/repos/flutter/samples/deployments",
      "created_at": "2018-06-08T21:28:03Z",
      "updated_at": "2025-02-25T04:26:03Z",
      "pushed_at": "2025-02-25T01:23:50Z",
      "git_url": "git://github.com/flutter/samples.git",
      "ssh_url": "git@github.com:flutter/samples.git",
      "clone_url": "https://github.com/flutter/samples.git",
      "svn_url": "https://github.com/flutter/samples",
      "homepage": "https://flutter.github.io/samples/",
      "size": 1053807,
      "stargazers_count": 17790,
      "watchers_count": 17790,
      "language": "Dart",
      "has_issues": true,
      "has_projects": false,
      "has_downloads": true,
      "has_wiki": false,
      "has_pages": true,
      "has_discussions": false,
      "forks_count": 7661,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 60,
      "license": {
          "key": "other",
          "name": "Other",
          "spdx_id": "NOASSERTION",
          "url": null,
          "node_id": "MDc6TGljZW5zZTA="
      },
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [],
      "visibility": "public",
      "forks": 7661,
      "open_issues": 60,
      "watchers": 17790,
      "default_branch": "main",
      "score": 1.0
    }
  ]
}
  ''';

  // total_countが0のデータが返ってきた場合
  static const String emptyJsonData = '''
  {
  "total_count": 0,
  "items": []
}
  ''';
}
